게시판 페이지 제작
naem-developers/naem-client pull request #41
Opened 2022-08-08 14:16 UTC by jwoo9928

게시판 첫 페이지 제작
 - 서치바 구현
 - tag 버튼 제작 완료
 - 키워드 선택 view 접기, 펼치기 기능 추가
 - 게시판별 tabs-view 제작
 - 화면에서 일부 벗어나있는 게시판 선택시 자동 스크롤
 - 시간순, 댓글순, 좋아요 순 선택 modal 제작,
 - 게시물 간단 viewer 제작
 - 게시물 최 상단으로 이동하는 버튼 제작 

![simulator_screenshot_81218955-C853-4F39-BDD0-40A2721DB82A](https://user-images.githubusercontent.com/51700184/183438537-324abc9e-6c00-49ca-9fad-84ef830b6bf7.png)
![simulator_screenshot_CFB9DB6F-48AE-40F9-A1B5-137453C84987](https://user-images.githubusercontent.com/51700184/183438677-ab673144-1b3f-467d-b61f-b42b829a350d.png)

2022-08-08 15:11 UTC, Jeyoung-Park commented
@jwoo9928 컨플릭 해결 부탁드려요! develop 최신화 이후 rebase 해주심 됩니다

2022-08-08 15:12 UTC, Jeyoung-Park commented on .gitignore
> +
@jwoo9928 이 항목들 gitignore 하신 이유 알 수 있을까요?

2022-08-08 15:12 UTC, Jeyoung-Park commented on package.json
> +    "react-native-pager-view": "5.4.25",
@jwoo9928  pager view는 어떤 역할을 하나요?

2022-08-08 15:14 UTC, Jeyoung-Park commented on package.json
> +    "react-native-tab-view": "3.1.1"
@jwoo9928 ^ 이 친구 빠져도 별 이슈 없을까요?

2022-08-08 15:16 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/SearchInput.tsx
> +      <TextInput
@jwoo9928 components/atoms/textinput 에 공통 textinput 컴포넌트가 있는데 이거 사용해도 괜찮을지 검토 바랍니다!
그리고 components/organisms/Searchbar에 Searchbar 컴포넌트 제가 만들어 놓은 거 있는데 이거 사용해도 좋을 것 같아요

2022-08-08 15:17 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/SearchInput.tsx
> +    backgroundColor: '#F5F5F5',
@jwoo9928 background 값 white아닌지 확인 부탁드리겠습니다. 그게 #f5f5f5는 피그마의 배경색상이라 잡히는 경우도 있어서 저도 헷갈린 적이 있습니다. THEME.BG로 배경색상 정의되어 있으니 이것도 참고 바랍니다

2022-08-08 15:18 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +  const keywords = DISABLED_TYPE;
DISABLED_TYPES 값을 그대로 사용하지 않으신 이유가 있으신가요?

2022-08-08 15:18 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +    calcuateTagLenth();
@jwoo9928 오타 발견이요!

2022-08-08 15:19 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +    for (let i = 0; i < keywords.length; i++) {
@jwoo9928 js에서 for문 쓰는 거는 별로 안 좋다고 들었던 것 같아요 forEach 문이나 reduce를 사용해보는 건 어떨까요?

2022-08-08 15:19 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +            console.log(item);
@jwoo9928 불필요한 로그는 지우면 좋을 것 같아요

2022-08-08 15:20 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +              <FlatList
flatlist에 keyextractor 누락된 것 같아요

2022-08-08 15:21 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +              <FlatList
@jwoo9928 tag와 같이 몇 개 없는 경우는 flatlist보다 map으로 구현하는 게 더 나을 수도 있을 것 같아요

2022-08-08 15:21 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +    backgroundColor: '#FFFFFF',
이것도 THEME.BG로 선택해도 좋을 것 같아요

2022-08-08 15:21 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +    paddingHorizontal: 16,
이 값은 const에 H_PADDING 값으로 정의해두었습니다. 사용하면 좋을 것 같아요 @jwoo9928

2022-08-08 15:22 UTC, Jeyoung-Park commented on src/components/board/post/ChooseSortView.tsx
> +                <TouchableOpacity
@jwoo9928 텍스트만 버튼인 경우는 `components/atoms/TextBtn`에 TextBtn 컴포넌트가 있습니다. 이거 사용하시면 코드가 더 깔끔해질 것 같아요

2022-08-08 15:24 UTC, Jeyoung-Park commented on src/components/board/post/Post.tsx
> +          {`·  좋아요 ${postedData.like}`}
여기 마진값이 아니라 두 칸 공백으로 표시하는 거 맞나요?

2022-08-08 15:25 UTC, Jeyoung-Park commented on src/components/board/post/Post.tsx
> +          {`댓글 ${postedData.comment}`}
Text 컴포넌트에서는 `댓글 {posted.comment}`로 표시해도 좋을 것 같아요

2022-08-08 15:46 UTC, Jeyoung-Park commented on src/pages/board/boards/ GuardianBoard.tsx
> +import BoardSearchBar from '@/components/board/boardSearchBar';
@jwoo9928 여기 각 게시판을 각각 페이지로 만드신 이유가 있으신가요? 하나의 페이지를 만들고 해당 게시판을 클릭했을 떄 적절한 데이터를 뿌려주는 형태로 만들면 더 효율적이지 않을까 해서 그런 방향으로 가는 게 어떨까 싶습니다.

2022-08-08 15:47 UTC, Jeyoung-Park commented on src/pages/board/boards/ GuardianBoard.tsx
> +import { Text, StyleSheet, View } from 'react-native';
@jwoo9928 공통 컴포넌트로 있는 Text를 사용하는 게 좋을 듯 합니다

2022-08-08 15:47 UTC, Jeyoung-Park commented on src/pages/board/boards/ GuardianBoard.tsx
> +    <View style={styles.container}>
@jwoo9928 page인데 SafeAreaview를 사용하시지 않은 이유가 있으신가요?

2022-08-08 15:48 UTC, Jeyoung-Park commented on src/pages/board/index.tsx
> +  const renderScene = SceneMap({
@jwoo9928 위에서 말씀드렸던 것 처럼 하나의 페이지만 만들고 props 등을 통해서 게시판 타입을 분류하는 게 더 깔끔할 것 같습니다 👍

2022-08-08 15:49 UTC, Jeyoung-Park commented on src/utils/array/index.ts
> +export const removeItemOfArray = (arr: Array<any>, item: any) => {
@jwoo9928 필터 함수로 구현해도 좋을 것 같다는 생각이 드네요!

2022-08-08 15:50 UTC, Jeyoung-Park commented on src/i18n/resources/ko.ts
> +  boards: {
@jwoo9928 오 저도 이거 챙겨보도록 노력하겠습니다! 감사합니다 👍

2022-08-08 15:51 UTC, Jeyoung-Park requested changes
고생 많으셨습니다! 리뷰 내용 확인해주시고 수정해야될 부분은 이 브랜치에 수정 이후 커밋 부탁드리겠습니다 🙏 
하시다가 모르시는 거 있으시면 편하게 물어봐주세요 ㅎㅎ

2022-08-09 01:35 UTC, jwoo9928 commented on package.json
> +    "react-native-pager-view": "5.4.25",
pager view는 tabview의 꼭 필요한 의존성 라이브러리 입니다

2022-08-09 01:36 UTC, jwoo9928 commented on package.json
> +    "react-native-tab-view": "3.1.1"
네 버전을 고정하고 싶으시면 빼셔도 됩니다

2022-08-09 01:36 UTC, jwoo9928 commented on src/components/board/boardSearchBar/SearchInput.tsx
> +    backgroundColor: '#F5F5F5',
아 넵 알겠습니다

2022-08-09 01:38 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +  const keywords = DISABLED_TYPE;
DISABLED_TYPE이 지금은 앱에 저장되어있는 값을 사용하고 있지만 추후 이 태그들이 서버에서 받아서 사용하지 않을까 생각해서 변수로 할당해서 추후 수정시 적용하려고 변수를 할당해서 사용했습니다

2022-08-09 01:40 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +    for (let i = 0; i < keywords.length; i++) {
array같은 경우 forEach보다 for이 빠르다고 해서 저는 array에서는 for을 쓰는 편입니다. linkedList같은 경우에는 forEach가 훨씬 빠릅니다

2022-08-09 01:42 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +              <FlatList
tag같은 경우 몇개까지 추가가 가능한지 저희가 limit가 있나요? 아니라면 저희가 설정해놓은 tag갯수도 꽤 되고 추후 서버에서 받아올경우 많아질 수 도 있을 것 같아서 flatList로 구현했습니다. 
keyExtractor같은 경우 item에 고유의 키값을 주는것으로 알고있는데 굳이 필요하지 않을것 같아서 추가하지 않았습니다

2022-08-09 01:45 UTC, jwoo9928 commented on src/pages/board/boards/ GuardianBoard.tsx
> +import BoardSearchBar from '@/components/board/boardSearchBar';
각 게시판별로 선택된 태그와 검색값, post의 순서를 따로 관리하려고 따로 만들었습니다. 해당 게시판을 클릭했을때 데이터를 뿌려주려고 하면 클릭시 마다 데이터를 다시 셋팅하고 api를 불러와야할것 같아서요

2022-08-09 01:46 UTC, jwoo9928 commented on src/pages/board/boards/ GuardianBoard.tsx
> +import { Text, StyleSheet, View } from 'react-native';
아 여기서는 text를 잘못 불러왔네요 수정하겠습니다

2022-08-09 01:46 UTC, jwoo9928 commented on src/pages/board/boards/ GuardianBoard.tsx
> +    <View style={styles.container}>
board컴포넌트는 tabview안에 들어가서 safeArea가 필요하지 않아서 입니다

2022-08-09 01:48 UTC, jwoo9928 commented on src/pages/board/index.tsx
> +  const renderScene = SceneMap({
위에 답변달았습니다 ㅎ

2022-08-09 09:26 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +    for (let i = 0; i < keywords.length; i++) {
@jwoo9928 js에서 array와 linkedlist가 구분되어 있나요? 

아래 게시물 보시면 map이나 reduce 같은 친구들이 성능이 더 좋은 것으로 나와 있습니다. 모던하게 작성하는 측면에서도 좋다라고 생각합니다!
https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/

2022-08-09 09:28 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +              <FlatList
@jwoo9928 보통 이런 태그 형태가 카드 뷰를 넘치도록까지 설계가 되지는 않으니 리미트가 있긴 할 겁니다. 기획적으로 확정을 하면 될 것 같습니다. 그리고 array에서 key를 넣어주는 게 좋듯이 flatlist에서도 keyExtractor는 넣는 게 좋을 것 같아요!

2022-08-09 09:31 UTC, Jeyoung-Park commented on src/pages/board/boards/ GuardianBoard.tsx
> +import BoardSearchBar from '@/components/board/boardSearchBar';
@jwoo9928 게시판 종류를 하나 추가할 때마다 새롭게 뷰를 만들어야하므로 다소 비효율적인 뷰라고 생각이 듭니다. 클릭 시 데이터를 세팅하는 경우는 이 게시판을 감싸는 상위 컴포넌트에서 진행하면 될 듯 합니다. 올려주심 pr에서는 board/index.tsx 파일이 컨테이너의 기능을 할 수 있겠네요!

2022-08-09 09:36 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +    for (let i = 0; i < keywords.length; i++) {
조금 더 보니가 for과 js array 메서드 간의 성능은 주장이 다양하네요 조금 더 찾아봐야될 것 같습니다
만약 성능이 비슷하다고 하더라도 깔끔함 측면에서 array 메서드가 더 낫다라고 생각합니다

2022-08-09 23:42 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +    for (let i = 0; i < keywords.length; i++) {
보통 단순 반복은 for, 배열의 순회는 forEach, 새배열을 얻으려면 map이라고 하니 이 기능은 새로운 배열을 얻는 경우임으로 map으로 변경하겠습니다

2022-08-09 23:51 UTC, jwoo9928 commented on src/components/board/boardSearchBar/SearchInput.tsx
> +    backgroundColor: '#F5F5F5',
수정완료

2022-08-10 00:09 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +    paddingHorizontal: 16,
수정 완료했습니다.

2022-08-10 00:14 UTC, jwoo9928 commented on src/pages/board/boards/ GuardianBoard.tsx
> +import { Text, StyleSheet, View } from 'react-native';
수정 완료

2022-08-10 00:14 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +    backgroundColor: '#FFFFFF',
수정완료

2022-08-10 00:14 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +              <FlatList
수정완료

2022-08-10 00:15 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +            console.log(item);
수정완료

2022-08-10 00:15 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +    for (let i = 0; i < keywords.length; i++) {
수정완료

2022-08-10 00:15 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +    calcuateTagLenth();
수정완료

2022-08-10 00:22 UTC, jwoo9928 commented on src/pages/board/boards/ GuardianBoard.tsx
> +import BoardSearchBar from '@/components/board/boardSearchBar';
현재 각 보드에서는 post와 searchBar를 공통으로 사용합니다. 제 말씀은 음.. 일단 tabView가 보드의 상위 컴포넌트인데 tabView에서 값을 넘기기에는 조금 불편한 구조를 가지고 있기도 하고 제 말씀은 데이터 셋팅의 문제 이외에 만약 게시판 별로 postView가 달라지거나 UI가 달라질 경우 한 보드에서 게시판 종류에 따라 postView를 변경해주어야 하는데 이럴경우 각 board를 여러개 만드는것과 board안에서 게시판 안에서 post가 여러개 전환 되는 경우와 무슨 차이인지 잘 모르겠습니다.

2022-08-16 08:03 UTC, jwoo9928 commented on src/pages/board/boards/ GuardianBoard.tsx
> +import BoardSearchBar from '@/components/board/boardSearchBar';
수정 완료

2022-08-16 12:36 UTC, Jeyoung-Park commented on .gitignore
> +
@jwoo9928 이 파일들이 gitignore에 포함된 이유 설명 부탁드리겠습니다!

2022-08-16 12:39 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +  const calcurateTagLenth = () => {
@jwoo9928  calcurateTagLenth -> calculateTagLength 이렇게 수정되어야 할 듯 합니다

2022-08-16 12:40 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +  const calcurateTagLenth = () => {
그리고 이 함수의 역할을 설명해주실 수 있나요?

2022-08-16 12:41 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +    paddingHorizontal: 16,
@jwoo9928 paddingHorizontal 값이 변경돼야 합니다! HorizontalPadding이라 H_PADDING 입니다!

2022-08-16 12:41 UTC, Jeyoung-Park commented on src/components/board/post/ChooseSortView.tsx
> +                <TouchableOpacity
@jwoo9928 이 내용 확인 부탁드려요!

2022-08-16 12:42 UTC, Jeyoung-Park commented on src/components/board/post/Post.tsx
> +  const shortening = useCallback(
@jwoo9928 텍스트 끝에 말줄임을 표현하시기 위함이신가요? flex, flexShrink, numOfLines 속성 등을 조합해서 구현이 가능해 보입니다.

2022-08-16 12:44 UTC, Jeyoung-Park commented on src/components/board/post/index.tsx
> +      <FlatList
@jwoo9928 여기도 keyExtractor 필요해 보입니다!

2022-08-16 12:45 UTC, Jeyoung-Park commented on src/pages/board/index.tsx
> +import HotBoard from '@pages/board//boards/HotBoard';
@jwoo9928 여기 경로가 이상하네요 
확인 부탁드려요

2022-08-16 12:45 UTC, Jeyoung-Park commented on src/pages/board/index.tsx
> +  const [routes] = useState([
이 routes를 useState로 관리하시는 이유가 있으신가요? @jwoo9928

2022-08-16 12:46 UTC, Jeyoung-Park commented on src/pages/board/boards/HotBoard.tsx
> +const HotBoard = () => {
@jwoo9928 이거 하나로 관리하게 된다면 HotBoard 대신에 컴포넌트명 수정하시는 게 좋을 것 같습니다. 
그냥 `Board`도 괜찮을 것 같고 적절한 네이밍으로 변경 제안드립니다!

2022-08-16 12:47 UTC, Jeyoung-Park commented on src/pages/board/index.tsx
> +    backgroundColor: '#FFFFFF',
@jwoo9928 여기 컬로도 그렇고 아래에 있는 컬로들도 THEME에 있는 컬러로 수정하면 좋을 것 같네요

2022-08-16 12:57 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +  const calcurateTagLenth = () => {
보시면 아시겠지만 각 태그 길이의 합이 화면의 넓이보다 크다면 다음줄로 태그를 넘기기 위해 계산하는 함수입니다

2022-08-16 12:59 UTC, jwoo9928 commented on src/components/board/post/Post.tsx
> +  const shortening = useCallback(
속성으로의 표현보다는 저는 글자수 제한이 더 괜찮을것 같습니다

2022-08-16 13:01 UTC, jwoo9928 commented on src/components/board/post/index.tsx
> +      <FlatList
수완

2022-08-16 13:07 UTC, jwoo9928 commented on src/pages/board/index.tsx
> +import HotBoard from '@pages/board//boards/HotBoard';
제가 보기에는 경로 올바른것 같습니다

2022-08-16 13:08 UTC, jwoo9928 commented on src/pages/board/index.tsx
> +  const [routes] = useState([
render시 재 선언 되지 않게 막았습니다

2022-08-16 13:09 UTC, jwoo9928 commented on src/pages/board/boards/HotBoard.tsx
> +const HotBoard = () => {
전에 저희가 이야기 현재는 하나로 관리하지만 나중에는 늘어날 수 도 있고 제가 보기에 컴포넌트명은 그렇게 중요한것 같지 않습니다. 왜냐하면 지금 보드는 하나이니까요 추후에 늘어난다면 이름이 중요한게 맞는것 같습니다

2022-08-16 13:11 UTC, jwoo9928 commented on src/pages/board/index.tsx
> +    backgroundColor: '#FFFFFF',
수완

2022-08-16 13:16 UTC, jwoo9928 commented on .gitignore
> +
pods를 사용시 무거워지기때문에 각 로컬에서 pod install로 pods를 생성하는게 맞지 않나 싶습니다
vendor는 저도 들었었지만 까먹었는데 웹팀에서 넣어달라고 했어서 넣어봤습니다

2022-08-16 13:28 UTC, Jeyoung-Park commented on .gitignore
> +
@jwoo9928 오호 넵 좋습니다!

2022-08-16 13:29 UTC, Jeyoung-Park commented on src/components/board/boardSearchBar/index.tsx
> +  const calcurateTagLenth = () => {
@jwoo9928 만약 그런 용도라면 flexWrap 속성 등을 이용해서 사용하는 것이 맞을 것 같습니다. 스타일 속성으로 대체할 수 있는 부분은 대체하면 좋을 것 같아요

2022-08-16 13:29 UTC, Jeyoung-Park commented on src/components/board/post/Post.tsx
> +  const shortening = useCallback(
@jwoo9928 js단에서 추가적인 로직이 들어가기 떄문에 스타일 속성으로 대체하는 것이 더 효율적이지 않을까 싶습니다! 혹시 글자수 제한을 선호하시는 이유가 있는지 궁금합니다!

2022-08-16 13:30 UTC, Jeyoung-Park commented on src/pages/board/index.tsx
> +import HotBoard from '@pages/board//boards/HotBoard';
@jwoo9928 슬래쉬가 연속으로 나오는데 맞는 건가요??

2022-08-16 13:30 UTC, Jeyoung-Park commented on src/pages/board/index.tsx
> +  const [routes] = useState([
@jwoo9928 그렇다면 컴포넌트 외부에서 상수로 선언하면 될 것 같습니다

2022-08-16 13:32 UTC, Jeyoung-Park commented on src/pages/board/boards/HotBoard.tsx
> +const HotBoard = () => {
@jwoo9928 현재 공통 보드로 사용되는 친구이기 떄문에 그에 걸맞는 파일명 및 컴포넌트명이 필요하다고 생각합니다. 만약 이 코드의 히스토리에 대해 잘 모르시는 분이 이 코드를 접한다고 했을 떄 이 네이밍에 대한 맥락을 파악하기 어려울 수도 있다고 생각합니다.

2022-08-20 06:46 UTC, jwoo9928 commented on src/components/board/boardSearchBar/index.tsx
> +  const calcurateTagLenth = () => {
다음 수정때 반영하겠습니다

2022-08-20 06:48 UTC, jwoo9928 commented on src/components/board/post/Post.tsx
> +  const shortening = useCallback(
home에서 작업하겠습니다

2022-08-20 06:49 UTC, jwoo9928 commented on src/pages/board/index.tsx
> +import HotBoard from '@pages/board//boards/HotBoard';
수완

2022-08-20 07:16 UTC, jwoo9928 commented on src/pages/board/boards/HotBoard.tsx
> +const HotBoard = () => {
수완

2022-08-20 07:16 UTC, Jeyoung-Park approved these changes
고생 많으셨습니다 🙏 🙏 🙏 🙏

2022-08-20 07:17 UTC, merged