게시판 상세의 게시판 내용 viewer제작
naem-developers/naem-client pull request #42
Opened 2022-08-08 14:18 UTC by jwoo9928

게시판 상세 페이지의 게시판 내용 viewer제작
 - 타이틀, id, time 출력
 - body출력 (임시)
 - tag 컴포넌트에서 색 반전 기능 추가 (disable시에만)
 - 하트 able, disable 기능

 - 댓글 수 출력
 - 공유하기 아이콘 추가

![simulator_screenshot_8153A388-512F-49E0-9FD7-750A697A2E02](https://user-images.githubusercontent.com/51700184/183439623-34933101-7350-4442-bcec-2fe5c67514aa.png)

2022-08-08 15:53 UTC, Jeyoung-Park commented on src/components/organisms/Header/index.tsx
> +  titleStyle?: ViewStyle;
@jwoo9928 오! 이렇게 필요하신 부분 있으시면 적용해주시면 됩니다. 감사합니다 👍

2022-08-08 15:55 UTC, Jeyoung-Park commented on src/assets/icons/icn_dotIcon.svg
> +<svg width="31" height="15" viewBox="0 0 31 15" fill="none" xmlns="http://www.w3.org/2000/svg">
@jwoo9928 이 친구는 네이밍을 snake_case로 통일해주면 좋을 것 같아요

2022-08-08 15:55 UTC, Jeyoung-Park commented on src/components/board/post/Post.tsx
> +              // disabled={true}
@jwoo9928 불필요한 주석은 제거 부탁드림다!

2022-08-08 15:56 UTC, Jeyoung-Park commented on src/components/board/post/index.tsx
> +      <TouchableOpacity
@jwoo9928 맨 위로 올리기 버튼 같은 친구는 공통 컴포넌트로 만들어도 좋겠네요!

2022-08-08 15:56 UTC, Jeyoung-Park commented on src/components/board/post/index.tsx
> +    width: 41,
@jwoo9928 android elevation이나 ios shadow 속성은 없었나요? 보통 플로팅 버튼에는 그림자 효과가 많이 적용돼서 여쭤봐요

2022-08-08 15:57 UTC, Jeyoung-Park commented on src/pages/board/BoardDetail.tsx
> +  const navigation = useNavigation();
@jwoo9928 저는 navigation을 props로 사용하고 있는데 재우님은 훅으로 호출하시는 군요! 이 부분에 대한 통일이 필요할 것 같네요 ㅎㅎ 
그리고 navigation 사용하실 때 ts에서는 타입 선언을 해줘야하는데요, 제가 작업한 부분 참고하시면 될 듯 합니다!

2022-08-08 15:58 UTC, Jeyoung-Park commented on src/pages/board/boards/dumys.ts
> +export const DumyPostData = [
@jwoo9928 앗 요거 스펠링 미스 났습니다!

2022-08-08 15:58 UTC, Jeyoung-Park commented on src/pages/board/index.tsx
> +    <SafeAreaView style={styles.container} edges={['top']}>
@jwoo9928 오 이 edges 속성은 어떤 역할을 하나요?

2022-08-08 15:59 UTC, Jeyoung-Park requested changes
@jwoo9928 고생 많으셨습니다! 이것도 conflict이 남아 있어 request changes로 남겼습니다.
그 #41 브랜치 이후에 작업된 내용을 pr로 올리신 거 같은데 나중에 머지하실 떄 안 꼬이게 잘 부탁드리겠습니다! 궁금하신 거 있으시면 편하게 물어보시고 혹시 필요하시다면 모각코 요청하셔도 됩니다 :)

2022-08-09 01:31 UTC, jwoo9928 commented on src/assets/icons/icn_dotIcon.svg
> +<svg width="31" height="15" viewBox="0 0 31 15" fill="none" xmlns="http://www.w3.org/2000/svg">
넵 알겠습니다

2022-08-09 01:31 UTC, jwoo9928 commented on src/components/board/post/index.tsx
> +      <TouchableOpacity
아 다른페이지에도 적용되나요? 공통으로 올리겠습니다

2022-08-09 01:32 UTC, jwoo9928 commented on src/components/board/post/index.tsx
> +    width: 41,
elevation이나 ios shadow각각 따로 적용되는데 그것보단 제가 사용해봤던 react-native-shadow-2라는 컴포넌트가 공통으로 사용하기에 좋더라구요 저희 앱의 header에도 그림자가 드러가던데 이 라이브러리를 사용하는것도 좋을것 같습니다

2022-08-09 01:33 UTC, jwoo9928 commented on src/pages/board/BoardDetail.tsx
> +  const navigation = useNavigation();
hook으로 호출시 타입선언 없이도 메소드 호출이 편리해서 사용했습니다 ㅎ

2022-08-09 01:33 UTC, jwoo9928 commented on src/pages/board/boards/dumys.ts
> +export const DumyPostData = [
앗 스펠링 미스 수정하겠습니다

2022-08-09 01:34 UTC, jwoo9928 commented on src/pages/board/index.tsx
> +    <SafeAreaView style={styles.container} edges={['top']}>
edges속성은 safeArea를 적용하고 싶은 부분만 적용할 수 있습니다. tabView에서 하단에도 safeArea를 적용시 빈공간이 생기게 되서 top에만 적용했습니다 (only ios)

2022-08-09 09:19 UTC, Jeyoung-Park commented on src/components/board/post/index.tsx
> +    width: 41,
오 좋네요! 나중에 pr로 올려주시죠!

2022-08-09 09:19 UTC, Jeyoung-Park commented on src/pages/board/BoardDetail.tsx
> +  const navigation = useNavigation();
@jwoo9928 아 훅으로 호출해도 마찬가지로 타입선언 필요합니다 나중에 메서드 사용하실 때 에러 뜰 거에요

2022-08-09 09:20 UTC, Jeyoung-Park commented on src/components/board/post/index.tsx
> +      <TouchableOpacity
@jwoo9928 당장은 게시판에만 사용되지만 적용될 가능성이 높은 친구라 그렇게 해도 좋을 것 같아요

2022-08-16 08:10 UTC, jwoo9928 commented on src/assets/icons/icn_dotIcon.svg
> +<svg width="31" height="15" viewBox="0 0 31 15" fill="none" xmlns="http://www.w3.org/2000/svg">
수정 완료

2022-08-16 08:12 UTC, jwoo9928 commented on src/components/board/post/index.tsx
> +      <TouchableOpacity
홈에서도 필요해서 홈 작업시 공통 컴포넌트로 만들겠습니다

2022-08-16 08:14 UTC, jwoo9928 commented on src/pages/board/BoardDetail.tsx
> +  const navigation = useNavigation();
수정 완료

2022-08-20 07:43 UTC, Jeyoung-Park approved these changes

2022-08-20 07:44 UTC, merged